# Variable Annotations
__version__: str

# Functions
def print_cache_size() -> None: ...
def get_string_item(name: str) -> str: ...
def set_string_item(name: str, item: str) -> None: ...
def get_binary_item(name: str) -> bytes | None: ...
def set_binary_item(name: str, value: bytes) -> None: ...
def get_string_item_decompressed(name: str) -> str: ...
def set_string_item_compressed(name: str, item: str) -> None: ...
def get_binary_item_decompressed(name: str) -> bytes | None: ...
def set_binary_item_compressed(name: str, value: bytes) -> None: ...

# Classes
class PyCache:
    def __init__(self, capacity: int, ttl_secs: int | None = None) -> None: ...
    def get(self, key: str) -> bytes | None: ...
    def set(self, key: str, value: bytes) -> None: ...

class PyAsyncCache:
    def __init__(self, capacity: int, ttl_secs: int | None = None) -> None: ...
    async def get(self, key: str) -> bytes | None: ...
    async def set(self, key: str, value: bytes) -> None: ...
